version: '3'

services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  app-2:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3001:3000"
    volumes:
      - .:/app
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
    - "80:80"
