version: '3'

services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
  app-2:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
    - "80:80"
  redis:
    image: redis
